# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    - id: safety
      name: safety
      entry: safety check --bare
      language: python
      pass_filenames: false
      language_version: python3
      types: [text]
    - id: black
      name: black
      entry: black
      language: python
      language_version: python3
      types: [python]