---
on:
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"

name: ci

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  poetry-version: 1.3.2
  python-version: 3.11

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install python ${{ env.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: "Install poetry ${{ env.poetry-version }}"
        uses: abatilo/actions-poetry@v2.1.1
        with:
          poetry-version: ${{ env.poetry-version }}

      - run: poetry config virtualenvs.in-project true
      - run: poetry install

      - run: poetry run safety check

  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install python ${{ env.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: "Install poetry ${{ env.poetry-version }}"
        uses: abatilo/actions-poetry@v2.1.1
        with:
          poetry-version: ${{ env.poetry-version }}

      - run: poetry config virtualenvs.in-project true
      - run: poetry install

      - run: poetry run black . --check

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install python ${{ env.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: "Install poetry ${{ env.poetry-version }}"
        uses: abatilo/actions-poetry@v2.1.1
        with:
          poetry-version: ${{ env.poetry-version }}

      - name: Copy .env
        run: cp .env.github .env

      - run: poetry config virtualenvs.in-project true
      - run: poetry install

      - run: poetry run coverage run -m pytest
      - run: poetry run coverage report